# Generated by Django 4.0.4 on 2022-05-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_suscriptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscriptor',
            name='idm',
        ),
    ]
