# Generated by Django 4.0.4 on 2022-05-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_suscriptor_idm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='t_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='t_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='t_title',
            new_name='title',
        ),
    ]
