# Generated by Django 4.0.4 on 2022-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_tip_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='icon',
            field=models.CharField(choices=[('fa-solid fa-droplet', 'agua'), ('fa-solid fa-wheat-awn', 'comida'), ('fa-solid fa-person-running', 'deporte'), ('fa-solid fa-comment-medical', 'medicamento'), ('fa-solid fa-comment', 'otros')], max_length=100),
        ),
    ]
