# Generated by Django 4.0.4 on 2022-05-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_link_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(choices=[('fa-solid fa-globe', 'web'), ('fa-solid fa-house-medical', 'salud'), ('fa-solid fa-link', 'otros')], max_length=100),
        ),
    ]
