# Generated by Django 4.0.4 on 2022-05-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0003_delete_prueba_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('cc_myself', models.BooleanField(verbose_name=False)),
                ('sending_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=200)),
                ('guide_name', models.CharField(max_length=200)),
                ('workshop_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
