# Generated by Django 4.0.4 on 2022-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0007_remove_contact_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presents',
            name='workshop_date',
            field=models.DateTimeField(),
        ),
    ]
