# Generated by Django 4.0.4 on 2022-05-14 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0008_alter_presents_workshop_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='presents',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
