# Generated by Django 4.0.4 on 2022-05-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0009_presents_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presents',
            name='picture',
        ),
    ]
