# Generated by Django 4.0.4 on 2022-05-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0010_remove_presents_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='presents',
            name='img_path',
            field=models.CharField(max_length=200, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
