# Generated by Django 4.0.4 on 2022-05-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0012_alter_presents_img_path_alter_presents_workshop_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='present',
            new_name='present_id',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
