# Generated by Django 4.0.4 on 2022-05-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0013_rename_order_orderdetail_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='present_id',
            new_name='present',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
